# Generated by Django 3.0.7 on 2020-09-13 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videotitle', models.CharField(max_length=100)),
                ('videodesc', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 9, 13, 3, 50, 53, 621442, tzinfo=utc))),
            ],
        ),
    ]
